[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
serde = { version = "1.0.214", features = ["serde_derive"] }
serde_yml = "0.0.12"
tokio = { version = "1.41.0", features = ["full", "process", "tokio-macros"] }
